const express = require('express')
const router = express.Router()
const controller = require('../controllers/hotel')
const uploadCloud = require('../config/cloudinary.config')
const validateHotel = require('../validations/hotel')
const validate = require('../middlewares/validate')
router.post('/', uploadCloud.array('images'), validateHotel.create(), validate, controller.create)
router.get('/:id', validateHotel.findOne(), validate, controller.findOne)
router.put('/public/:id', validateHotel.findOne(), validate, controller.togglePublic)
router.put('/:id', validateHotel.update(), validate, controller.update)
module.exports = router
