const router = require('express').Router()
const auth = require('./auth')
const user = require('./user')
const employee = require('./employee')
const client = require('./client')
const serviceManager = require('./serviceManager')
const province = require('./province')
const amenitiesHotel = require('./amenitiesHotel')
const hotel = require('./hotel')
const image = require('./image')
const room = require('./room')
const restaurant = require('./restaurant')
const corpTour = require('./corpTour')
const destiantionTravel = require('./destinationTravel')
const itinerary = require('./itinerary')
const comment = require('./comment')
router.get('/status', (req, res) => {
    res.status(200).json({ status: 'Status OKE' })
})
router.use('/auth', auth)
router.use('/user', user)
router.use('/employee', employee)
router.use('/client', client)
router.use('/service-manager', serviceManager)
router.use('/province', province)
router.use('/amenitiesHotel', amenitiesHotel)
router.use('/hotel', hotel)
router.use('/image', image)
router.use('/room', room)
router.use('/restaurant', restaurant)
router.use('/corp-tour', corpTour)
router.use('/destination-travel', destiantionTravel)
router.use('/itinerary', itinerary)
router.use('/comment', comment)

module.exports = router
